name: pipeline-umi-amplicon
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.8.16
  - snakemake
  - minimap2
  - samtools
  - tabix
  - seqkit
  - pysam
  - bedtools
  - vsearch
  - varscan
  - medaka
  - pip
  - pip:
    - catfishq
